language: c

before_install:
  - sudo apt-get update -qq

  # 32bit compatibility
  - sudo apt-get install -qq libc6:i386 libncurses5:i386 libstdc++6:i386

  # BennuGD dependencies
  - sudo apt-get install -qq zlib1g:i386 libssl1.0.0:i386 libsdl1.2debian:i386 libsdl-mixer1.2:i386

install:
  - wget http://www.bennugd.org/downloads/bgd-1.0.0-r335-linux.tar.gz
  - tar -zxvf bgd-1.0.0-r335-linux.tar.gz
  - chmod +x bin/*
  - sudo mv bin/* /usr/local/bin/
  - sudo mv lib/* /usr/local/lib/
  - sudo ldconfig -v

before_script:
  - sudo chmod +x build.sh test/test.sh
  - ./build.sh

script:
  - cd test && ./test.sh && cd ..

before_deploy: ls -la
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: tilescroll.prg
  skip_cleanup: true
  on:
    tags: true
